DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS FOLDER;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS ITEM_TYPE;
DROP TABLE IF EXISTS PREFERENCES;
DROP TABLE IF EXISTS AUDIT;

CREATE TABLE USER (
    USER_ID INTEGER PRIMARY KEY,
    EMAIL VARCHAR(250) UNIQUE,
    NAME VARCHAR(250),
    PASSWORD VARCHAR(250),
    PASSWORD_HINT VARCHAR(250),
    PREFERENCES_ID INTEGER,
    EMAIL_CONFIRMED BOOLEAN DEFAULT 'N',
    FOREIGN KEY (PREFERENCES_ID) REFERENCES PREFERENCES(ID) ON DELETE CASCADE
);

            
CREATE TABLE FOLDER (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    FOLDER_NAME VARCHAR(250),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
);

CREATE TABLE ITEM (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    FOLDER_ID INTEGER,
    ITEM_TYPE_ID INTEGER,
    NAME VARCHAR(250),
    USERNAME VARCHAR(250),
    PASSWORD VARCHAR(250),
    URI VARCHAR(250),
    NOTES VARCHAR(250),
    CUSTOM_FIELD_NAME VARCHAR(255),
    CUSTOM_FIELD_TYPE INTEGER,
    CUSTOM_FIELD_VALUE VARCHAR(250),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLDER_ID) REFERENCES FOLDER(ID) ON DELETE CASCADE
    );

CREATE TABLE ITEM_TYPE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_TYPE VARCHAR(250) 
    );

CREATE TABLE PREFERENCES (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    VAULT_TIMEOUT TIME,
    THEME_ID INTEGER,
    LANGUAGE_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
    );

CREATE TABLE AUDIT (
    ID INTEGER PRIMARY KEY,
    ENTITY_TYPE_ID VARCHAR(50),
    ENTITY_ID INTEGER,
    ACTION_TYPE VARCHAR(50),
    USER_ID INTEGER,
    TIMESTAMP DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE
    );