DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ITEM;


CREATE TABLE USER (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME Text NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    PASSWORD_HINT TEXT NOT NULL,
    EMAIL_CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE ITEM (
    ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_NAME TEXT NOT NULL,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    URI TEXT NOT NULL,
    NOTE TEXT NOT NULL
);